
const $=id=>document.getElementById(id);let candles=[],lastReport=null,lastMatrix=null;
function log(x){$('log').textContent=typeof x==='string'?x:JSON.stringify(x,null,2)}
function setStatus(x){$('status').textContent=x}
function tfName(sec){return ({300:'M5',900:'M15',1800:'M30',3600:'H1'})[sec]||sec+'s'}
function barsFor(sec,min){return Math.max(1,Math.round(min*60/sec))}
function mean(a){return a.length?a.reduce((x,y)=>x+y,0)/a.length:NaN}
function sd(a){if(a.length<2)return NaN;const m=mean(a);return Math.sqrt(mean(a.map(x=>(x-m)**2)))}
function percentile(a,p){if(!a.length)return NaN;const s=[...a].sort((x,y)=>x-y),i=(s.length-1)*p/100,b=Math.floor(i),r=i-b;return s[b]+(s[b+1]??s[b]-s[b])*r}
function ema(vals,n){const out=Array(vals.length).fill(null);if(vals.length<n)return out;let e=mean(vals.slice(0,n));out[n-1]=e;const k=2/(n+1);for(let i=n;i<vals.length;i++){e=vals[i]*k+e*(1-k);out[i]=e}return out}
function atr(cs,n=14){const tr=cs.map((c,i)=>i?Math.max(c.high-c.low,Math.abs(c.high-c.open),Math.abs(c.low-c.open)):c.high-c.low);const out=Array(cs.length).fill(null);if(cs.length<n)return out;let a=mean(tr.slice(0,n));out[n-1]=a;for(let i=n;i<cs.length;i++){a=(a*(n-1)+tr[i])/n;out[i]=a}return out}
function rsi(cs,n=14){const out=Array(cs.length).fill(null);if(cs.length<=n)return out;let g=0,l=0;for(let i=1;i<=n;i++){const d=cs[i].close-cs[i-1].close;g+=Math.max(0,d);l+=Math.max(0,-d)}g/=n;l/=n;out[n]=l===0?100:100-100/(1+g/l);for(let i=n+1;i<cs.length;i++){const d=cs[i].close-cs[i-1].close;g=(g*(n-1)+Math.max(0,d))/n;l=(l*(n-1)+Math.max(0,-d))/n;out[i]=l===0?100:100-100/(1+g/l)}return out}
function features(cs){const close=cs.map(c=>c.close),a=atr(cs,14),e9=ema(close,9),e21=ema(close,21),e12=ema(close,12),e26=ema(close,26),mac=e12.map((v,i)=>v==null||e26[i]==null?null:v-e26[i]),sig=ema(mac.map(v=>v??close[0]),9),r=rsi(cs,14),out=[];for(let i=0;i<cs.length;i++){const c=cs[i],rng=c.high-c.low,body=Math.abs(c.close-c.open);let vol=null;if(i>=20){const rs=[];for(let j=i-19;j<=i;j++)rs.push(Math.log(close[j]/close[j-1]));vol=sd(rs)}const mid=i>=20?mean(close.slice(i-19,i+1)):null,ss=i>=20?sd(close.slice(i-19,i+1)):null;out.push({atrPct:a[i]!=null?a[i]/close[i]:null,rsiCentered:r[i]!=null?(r[i]-50)/50:null,emaSpread:e9[i]!=null&&e21[i]!=null?(e9[i]-e21[i])/close[i]:null,macdHistogram:mac[i]!=null&&sig[i]!=null?(mac[i]-sig[i])/close[i]:null,adxDirection:null,bollingerPosition:mid!=null&&ss?((close[i]-(mid-2*ss))/(4*ss)):null,bollingerWidthPct:mid?((4*ss)/mid):null,roc:i>=12?(close[i]/close[i-12]-1):null,bodyPct:body/Math.max(close[i],1e-12),rangePct:rng/Math.max(close[i],1e-12),closeLocation:rng?(close[i]-c.low)/rng:null,volatility20:vol})}return out}
function auc(scores,ys){const a=[];for(let i=0;i<scores.length;i++)if(Number.isFinite(scores[i]))a.push([scores[i],ys[i]]);let pos=a.filter(x=>x[1]===1).length,neg=a.length-pos;if(!pos||!neg)return NaN;a.sort((x,y)=>x[0]-y[0]);let rankSum=0;for(let i=0;i<a.length;i++)if(a[i][1]===1)rankSum+=i+1;return (rankSum-pos*(pos+1)/2)/(pos*neg)}
function wilson(w,n){if(!n)return [NaN,NaN];const z=1.96,p=w/n,den=1+z*z/n,ctr=(p+z*z/(2*n))/den,half=z*Math.sqrt(p*(1-p)/n+z*z/(4*n*n))/den;return [ctr-half,ctr+half]}
function evalSet(cs,fs,start,end,hMin,low,high,look,orient,tfSec){const h=barsFor(tfSec,hMin),featureKey=$('feature').value,rows=[];let candidateRows=0,finiteFeatureRows=0,insufficientHistoryRows=0,noneRows=0;for(let i=start+look;i<end-h;i++){candidateRows++;const v=fs[i][featureKey];if(!Number.isFinite(v))continue;finiteFeatureRows++;const hist=[];for(let j=Math.max(start,i-look);j<i;j++){const x=fs[j][featureKey];if(Number.isFinite(x))hist.push(x)}if(hist.length<30){insufficientHistoryRows++;continue}const p=hist.filter(x=>x<=v).length/hist.length*100;let dir='NONE';if(p<=low)dir=orient==='INVERSE'?'CALL':'PUT';else if(p>=high)dir=orient==='INVERSE'?'PUT':'CALL';if(dir==='NONE'){noneRows++;continue}const entry=cs[i].close,future=cs[i+h].close,win=(dir==='CALL'&&future>entry)||(dir==='PUT'&&future<entry),score=orient==='INVERSE'?-v:v;rows.push({i,ts:cs[i].time,feature:v,percentile:p,dir,entry,future,win,score})}rows.audit={candidateRows,finiteFeatureRows,insufficientHistoryRows,noneRows,signalRows:rows.length,horizonCandles:h,featureKey,start,end};return rows}
function aggregateCandles(cs,tfSec){if(tfSec===Number($('tf').value))return cs;const buckets=new Map();for(const c of cs){const key=Math.floor(c.time/tfSec)*tfSec;const prev=buckets.get(key);if(!prev)buckets.set(key,{time:key,open:c.open,high:c.high,low:c.low,close:c.close});else{prev.high=Math.max(prev.high,c.high);prev.low=Math.min(prev.low,c.low);prev.close=c.close}}return [...buckets.values()].sort((a,b)=>a.time-b.time)}
function datasetForTimeframe(sec){const baseSec=Number($('tf').value);if(sec<baseSec)return null;return aggregateCandles(candles,sec)}
function runCell(sec,min){const cs=datasetForTimeframe(sec);if(!cs||cs.length<60)return {tf:tfName(sec),horizon:min,error:`Dataset carregado em ${tfName(baseSecForMatrix())} não permite derivar ${tfName(sec)}.`};const fs=features(cs),h=barsFor(sec,min);if(cs.length<=h+30)return {tf:tfName(sec),horizon:min,error:`Poucos candles para ${tfName(sec)} +${min}m.`};const baseStart=Math.floor(cs.length*.0),baseEnd=Math.floor(cs.length*.8);const rows=evalSet(cs,fs,baseStart,baseEnd,min,Number($('low').value),Number($('high').value),Number($('lookback').value),$('orientation').value,sec);const m=metrics(rows);return {tf:tfName(sec),horizon:min,trades:m.trades,wr:m.wr,skill:m.skill,auc:m.auc,dir:m.skill>=0?'ALIGNED':'OPPOSED',wf:m.trades>=20?'OBSERVE':'THIN'} }
function baseSecForMatrix(){return Number($('tf').value)}
function metrics(rows){if(!rows.length)return {n:0,trades:0,wr:NaN,skill:NaN,auc:NaN,exp:NaN,dd:NaN,ci:[NaN,NaN]};let w=rows.filter(r=>r.win).length,n=rows.length,pnl=0,peak=0,dd=0;for(const r of rows){pnl+=r.win?1:-1;peak=Math.max(peak,pnl);dd=Math.max(dd,peak-pnl)}return {n,trades:n,wr:w/n,skill:w/n-.5,auc:auc(rows.map(r=>r.score),rows.map(r=>r.win?1:0)),exp:(w-(n-w))/n,dd,ci:wilson(w,n)}}
function splitReport(cs,fs){const n=cs.length,tfSec=Number($('tf').value),train=Math.floor(n*Number($('trainPct').value)/100),val=train+Math.floor(n*Number($('valPct').value)/100),args=[Number($('horizon').value),Number($('low').value),Number($('high').value),Number($('lookback').value),$('orientation').value,tfSec];return {train:evalSet(cs,fs,0,train,...args),validation:evalSet(cs,fs,train,val,...args),holdout:evalSet(cs,fs,val,n,...args)}}
function fmt(x,p=2){return Number.isFinite(x)?(x*100).toFixed(p)+'%':'—'}
function renderAudit(rep){const box=$('audit');if(!box)return;const labels={train:'Treino',validation:'Validação',holdout:'Holdout'};box.innerHTML='<table><thead><tr><th>Split</th><th>Candidatas</th><th>Feature válida</th><th>Histórico insuf.</th><th>NONE</th><th>Sinais</th></tr></thead><tbody>'+Object.entries(rep).map(([name,rows])=>{const a=rows.audit||{};return `<tr><td>${labels[name]||name}</td><td>${a.candidateRows??0}</td><td>${a.finiteFeatureRows??0}</td><td>${a.insufficientHistoryRows??0}</td><td>${a.noneRows??0}</td><td>${a.signalRows??0}</td></tr>`}).join('')+'</tbody></table>';}
function renderReport(rep){const body=$('results');body.innerHTML='';for(const [name,rows] of Object.entries(rep)){const m=metrics(rows),tr=document.createElement('tr');tr.innerHTML=`<td>${name}</td><td>${m.n}</td><td>${m.trades}</td><td>${fmt(m.wr)}</td><td>${fmt(m.skill)}</td><td>${Number.isFinite(m.auc)?m.auc.toFixed(3):'—'}</td><td>${Number.isFinite(m.exp)?m.exp.toFixed(3):'—'}</td><td>${m.dd}</td>`;body.appendChild(tr)}const hm=metrics(rep.holdout);$('trades').textContent=hm.trades;$('wr').textContent=fmt(hm.wr);$('skill').textContent=fmt(hm.skill);$('auc').textContent=Number.isFinite(hm.auc)?hm.auc.toFixed(3):'—';$('ci').textContent=`IC95% ${fmt(hm.ci[0])} — ${fmt(hm.ci[1])}`;$('hypoTag').textContent='executada';$('summary').textContent=`Holdout: ${hm.trades} sinais, win rate ${fmt(hm.wr)}, skill ${fmt(hm.skill)}, AUC ${Number.isFinite(hm.auc)?hm.auc.toFixed(3):'—'}. Isto é direção sobre close futuro, não P&L real.`;renderSignals(rep.holdout)}
function renderSignals(rows){$('signals').innerHTML=rows.slice(-30).reverse().map(r=>`<tr><td>${new Date(r.ts*1000).toLocaleString('pt-PT')}</td><td>${$('feature').selectedOptions[0].text}</td><td>${r.percentile.toFixed(1)}%</td><td class="${r.dir==='CALL'?'good':'bad'}">${r.dir}</td><td>${r.entry.toFixed(5)}</td><td>${r.future.toFixed(5)}</td><td class="${r.win?'good':'bad'}">${r.win?'WIN':'LOSS'}</td></tr>`).join('')||'<tr><td colspan="7" class="muted">Sem sinais.</td></tr>'}
async function fetchCandlePage(sec,count,end='latest',reqId=1){setStatus('CONNECTING');$('conn').textContent='connecting';const ws=new WebSocket(`wss://ws.derivws.com/websockets/v3?app_id=${encodeURIComponent($('appId').value.trim()||'1089')}`);return await new Promise((resolve,reject)=>{const timer=setTimeout(()=>{ws.close();reject(new Error('Timeout ao pedir candles'))},15000);let settled=false;ws.onopen=()=>{ $('conn').textContent='open';ws.send(JSON.stringify({ticks_history:$('symbol').value,adjust_start_time:1,count:Math.min(5000,count),granularity:sec,end,style:'candles',req_id:reqId}));};ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.error){if(!settled){settled=true;clearTimeout(timer);ws.close();reject(new Error(m.error.message||'Deriv error'));}return}if(m.msg_type==='candles'){if(!settled){settled=true;clearTimeout(timer);ws.close();resolve((m.candles||[]).map(c=>({time:Number(c.epoch),open:Number(c.open),high:Number(c.high),low:Number(c.low),close:Number(c.close)})).filter(c=>[c.time,c.open,c.high,c.low,c.close].every(Number.isFinite)).sort((a,b)=>a.time-b.time));}}};ws.onerror=()=>{if(!settled){settled=true;clearTimeout(timer);ws.close();reject(new Error('WebSocket error'))}}})}
async function fetchCandles(sec,count){const requested=Math.max(1,Math.floor(count));const pages=[];const pageSizes=[];let end='latest';let remaining=requested;let previousOldest=null;let safety=0;while(remaining>0&&safety<100){safety++;const pageSize=Math.min(5000,remaining);const before=requested-remaining; $('loadProgress').textContent=`A carregar: ${before.toLocaleString('pt-PT')} / ${requested.toLocaleString('pt-PT')} candles · bloco ${safety}`;const page=await fetchCandlePage(sec,pageSize,end,safety);if(!page.length)break;pages.push(...page);pageSizes.push(page.length);const oldest=page[0].time;if(previousOldest!==null&&oldest>=previousOldest)break;previousOldest=oldest;remaining=Math.max(0,remaining-page.length);if(remaining<=0)break;end=String(oldest-1);$('loadProgress').textContent=`A carregar: ${Math.min(requested,requested-remaining).toLocaleString('pt-PT')} / ${requested.toLocaleString('pt-PT')} candles · bloco ${safety} (${page.length} recebidos)`;await new Promise(r=>setTimeout(r,120));}const dedup=new Map(pages.map(c=>[c.time,c]));const out=[...dedup.values()].sort((a,b)=>a.time-b.time).slice(-requested);$('loadProgress').textContent=`Carregado: ${out.length.toLocaleString('pt-PT')} / ${requested.toLocaleString('pt-PT')} candles · ${pageSizes.length} bloco(s) · páginas: [${pageSizes.join(', ')}]`;window.__lastFetchDiagnostics={requested,loaded:out.length,pages:pageSizes,complete:out.length>=requested,first:out[0]||null,last:out[out.length-1]||null};return out}
$('fetch').onclick=async()=>{try{setStatus('LOADING');$('requested').textContent=Number($('count').value).toLocaleString('pt-PT');$('loaded').textContent='0';$('pages').textContent='0';$('coverage').textContent='a carregar';$('firstDate').textContent='—';$('lastDate').textContent='—';log('A carregar histórico com paginação automática...');candles=await fetchCandles(Number($('tf').value),Number($('count').value));$('n').textContent=candles.length;$('loaded').textContent=candles.length.toLocaleString('pt-PT');$('pages').textContent=(window.__lastFetchDiagnostics?.pages?.length||0);$('firstDate').textContent=candles[0]?new Date(candles[0].time*1000).toLocaleString('pt-PT'):'—';$('lastDate').textContent=candles[candles.length-1]?new Date(candles[candles.length-1].time*1000).toLocaleString('pt-PT'):'—';$('coverage').textContent=candles.length>=Number($('count').value)?'pedido completo':'histórico disponível menor que o pedido';$('matrixHint').textContent='A matriz usa apenas o dataset carregado; não faz novos pedidos à Deriv.';$('run').disabled=candles.length<250;$('matrix').disabled=candles.length<250;$('download').disabled=true;setStatus('READY');log({symbol:$('symbol').value,timeframe:tfName(Number($('tf').value)),requested:Number($('count').value),candles:candles.length,pages:window.__lastFetchDiagnostics?.pages||[],first:candles[0],last:candles[candles.length-1]})}catch(e){setStatus('ERROR');$('conn').textContent='error';$('loadProgress').textContent='Falha no carregamento';log(String(e.stack||e))}};
$('run').onclick=()=>{try{if(!candles.length)throw new Error('Carregue candles antes de executar a hipótese.');setStatus('RUNNING');const fs=features(candles),rep=splitReport(candles,fs);lastReport=rep;renderAudit(rep);renderReport(rep);$('download').disabled=false;setStatus('DONE');log({type:'hypothesis',source:'loaded_dataset_only',feature:$('feature').value,orientation:$('orientation').value,horizonMinutes:Number($('horizon').value),timeframe:tfName(Number($('tf').value)),datasetCandles:candles.length,audit:{train:rep.train.audit,validation:rep.validation.audit,holdout:rep.holdout.audit},metrics:{train:metrics(rep.train),validation:metrics(rep.validation),holdout:metrics(rep.holdout)}})}catch(e){setStatus('ERROR');log(String(e.stack||e))}};
function runCell(sec,min){const cs=datasetForTimeframe(sec);if(!cs||cs.length<60)return {tf:tfName(sec),horizon:min,error:`Dataset carregado em ${tfName(baseSecForMatrix())} não permite derivar ${tfName(sec)}.`};const fs=features(cs),h=barsFor(sec,min);if(cs.length<=h+30)return {tf:tfName(sec),horizon:min,error:`Poucos candles para ${tfName(sec)} +${min}m.`};const baseEnd=Math.floor(cs.length*.8);const rows=evalSet(cs,fs,0,baseEnd,min,Number($('low').value),Number($('high').value),Number($('lookback').value),$('orientation').value,sec);const m=metrics(rows);return {tf:tfName(sec),horizon:min,trades:m.trades,wr:m.wr,skill:m.skill,auc:m.auc,dir:m.trades===0?'NO_SIGNAL':(m.skill>=0?'ALIGNED':'OPPOSED'),wf:m.trades>=20?'OBSERVE':'THIN'} }
$('matrix').onclick=async()=>{try{setStatus('MATRIX');$('matrixBody').innerHTML='<tr><td colspan="5">A analisar o dataset já carregado…</td></tr>';if(!candles.length)throw new Error('Carregue candles antes de executar a matriz.');const baseSec=Number($('tf').value),tfs=[300,900,1800,3600],mins=[15,30,60,120],out=[];for(const sec of tfs){const row=[];for(const min of mins){if(sec<baseSec||min*60<sec){row.push(null);continue}row.push(runCell(sec,min));await new Promise(r=>setTimeout(r,0))}out.push(row)}lastMatrix=out;renderMatrix(out);setStatus('DONE');log({type:'matrix',source:'loaded_dataset_only',baseTimeframe:tfName(baseSec),requestedCandles:candles.length,derivedTimeframes:tfs.filter(sec=>sec>=baseSec).map(tfName),matrix:out})}catch(e){setStatus('ERROR');log(String(e.stack||e))}};
function renderMatrix(out){$('matrixBody').innerHTML='';const mins=[15,30,60,120];out.forEach((row,i)=>{const tr=document.createElement('tr');tr.innerHTML='<th>'+tfName([300,900,1800,3600][i])+'</th>'+row.map(c=>{if(!c)return '<td><div class="cell muted">incompatível</div></td>';if(c.error)return `<td><div class="cell muted"><div class="small">${c.error}</div></div></td>`;const tone=c.dir==='ALIGNED'?'good':c.dir==='OPPOSED'?'bad':'muted';return `<td><div class="cell"><div class="dir ${tone}">${c.dir}</div><div>WR ${fmt(c.wr)} · Skill ${fmt(c.skill)}</div><div>AUC ${Number.isFinite(c.auc)?c.auc.toFixed(3):'—'} · N ${c.trades??0}</div><div class="small">${c.wf}</div></div></td>`}).join('');$('matrixBody').appendChild(tr)})}
$('download').onclick=()=>{const data={version:'1.1',generatedAt:new Date().toISOString(),config:{symbol:$('symbol').value,timeframe:tfName(Number($('tf').value)),feature:$('feature').value,orientation:$('orientation').value,horizon:Number($('horizon').value),low:Number($('low').value),high:Number($('high').value),lookback:Number($('lookback').value),trainPct:Number($('trainPct').value),validationPct:Number($('valPct').value)},dataset:{candles:candles.length,fetchDiagnostics:window.__lastFetchDiagnostics||null},report:Object.fromEntries(Object.entries(lastReport||{}).map(([k,v])=>[k,{metrics:metrics(v),audit:v.audit||null,signals:v}])),matrix:lastMatrix};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download='x-one-forex-research-report.json';a.click()};
